package com.soccerDatabase;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by vegito2002 on 12/24/16.
 */
public class ManualDataGenerator {
    public Map<String, List<String>> manualSetPlayerMembership() {
        Map<String, List<String>> result = new HashMap<String,List<String>>();

        result.put("Manchester United", Arrays.asList("David de Gea",
                "Sergio Romero",
                "Sam Johnstone",
                "Eric Bailly",
                "Daley Blind",
                "Luke Shaw",
                "Chris Smalling",
                "Marcos Rojo",
                "Matteo Darmian",
                "Phil Jones",
                "Antonio Valencia",
                "Paul Pogba",
                "Henrikh Mkhitaryan",
                "Juan Mata",
                "Ander Herrera",
                "Morgan Schneiderlin",
                "Marouane Fellaini",
                "Ashley Young",
                "Jesse Lingard",
                "Bastian Scheweinsteiger",
                "Michael Carrick",
                "Timothy Fosu-Mensah",
                "Anthony Martial",
                "Wayne Rooney",
                "Memphis Depay",
                "Zlatan Ibrahimovic",
                "Marcus Dashford"));

        result.put("Burnley", Arrays.asList("Tom Heaton",
                "Nick Pope",
                "Paul Robinson",
                "Micheal Keane",
                "James Tarkowski",
                "Kevin Long",
                "Ben Mee",
                "Stephen Ward",
                "Jon Flanagan",
                "Matthew Lowton",
                "Tendayi Darikwa",
                "Steven Defour",
                "Jeff Hendrick",
                "Dean Marney",
                "George Boyd",
                "Scott Arfield",
                "Micheal Kightly",
                "Johann Berg Gudmundsson",
                "Andre Gray",
                "Patrick Bamford",
                "Sam Vokes",
                "Ashley Barnes"));

        result.put("Arsenal", Arrays.asList("Petr Cech",
                "David Ospina",
                "Emiliano Martinez",
                "Matt Macey",
                "Shkodran Mustafi",
                "Laurent Koscielny",
                "Gabriel Paulista",
                "Per Mertesacker",
                "Rob Holding",
                "Nacho Monreal",
                "Kieran Gibbs",
                "Hector Bellerin",
                "Carl Jenkinson",
                "Mathieu Debuchy",
                "Francis Coquelin",
                "Mohamed Elneny",
                "Aaron Ramsey",
                "Granit Xhaka",
                "Santi Cazorla",
                "Mesut Oezil",
                "Alex Iwobi",
                "Alex Oxlade-Chamberlain",
                "Alexis Sanchez",
                "Theo Walcott",
                "Olivier Giroud",
                "Lucas Perez",
                "Danny Welbeck",
                "Yaya Sanogo",
                "Chuba Akpom"));

        result.put("Leicester City", Arrays.asList("Kasper Schmeichel",
                "Ron-Robert Zieler",
                "Ben Hamer",
                "Robert Huth",
                "Wes Morgan",
                "Yohan Benalouane",
                "Marcin Wasilewski",
                "Jeffrey Schlupp",
                "Christian Fuchs",
                "Ben Chilwell",
                "Danny Simpson",
                "Luis Hernandez",
                "Nampalys Mendy",
                "Daniel Amartey",
                "Danny Drinkwater",
                "Andy King",
                "Matty James",
                "Marc Albrighton",
                "Bartosz Kapustka",
                "Demarai Gray",
                "Riyad Mahrez",
                "Islam Slimani",
                "Jamie Vardy",
                "Ahmed Musa",
                "Shinji Okazaki",
                "Leonardo Ulloa"));

        result.put("Chelsea", Arrays.asList("Thibaut Courtois",
                "Asmir Begovic",
                "Eduardo",
                "David Luiz",
                "Kurt Zouma",
                "Gary Cahill",
                "John Terry",
                "Cesar Azpilicueta",
                "Marcos Alonso",
                "Kenedy",
                "Branislav Ivanovic",
                "Todd Kane",
                "Ola Aina",
                "Nemanja Matic",
                "N'Golo Kante",
                "John Mikel Obi",
                "Nathaniel Chalobah",
                "Cesc Fabregas",
                "Marco van Ginkel",
                "Ruben Loftus-Cheek",
                "Oscar",
                "Eden Hazard",
                "Willian",
                "Pedro",
                "Victor Moses",
                "Diego Costa",
                "Michy Batshuayi"));

        result.put("Manchester City", Arrays.asList("Claudio Bravo",
                "Willy Caballero",
                "Angus Gunn",
                "John Stones",
                "Nicolas Otamendi",
                "Vincent Kompany",
                "Aleksandar Kolarov",
                "Gael Clichy",
                "Pablo Zabaleta",
                "Bacary Sagna",
                "Fernando",
                "Ilkay Gundogan",
                "Fernandinho",
                "Yaya Toure",
                "Fabian Delph",
                "Kevin De Bruyne",
                "David Silva",
                "Leroy Sane",
                "Nolito",
                "Jesus Navas",
                "Raheem Sterling",
                "Sergio Aguero",
                "Kelechi Iheanacho"));

        result.put("Southampton", Arrays.asList("Fraser Forster",
                "Alex McCarthy",
                "Stuart Taylor",
                "Virgil van Dijk",
                "Jose Fonte",
                "Florin Gardos",
                "Maya Yoshida",
                "Jack Stephens",
                "Ryan Bertrand",
                "Matt Targett",
                "Cedric Soares",
                "Cuco Martina",
                "Jordy Clasie",
                "Oriol Romeu",
                "James Ward-Prowse",
                "Pierre-Emile Hojbjerg",
                "Steven Davis",
                "Harrison Reed",
                "Jeremy Pied",
                "Sam McQueen",
                "Sofiane Boufal",
                "Dusan Tadic",
                "Nathan Redmond",
                "Lloyd Isgrove",
                "Jay Rodriguez",
                "Charlie Austin",
                "Shane Long"));

        result.put("Sunderland", Arrays.asList("Vito Mannone",
                "Mika",
                "Jordan Pickford",
                "Lamine Kone",
                "Papy Djilobodji",
                "Jason Denayer",
                "Paddy McNair",
                "John O'Shea",
                "Patrick van Aanholt",
                "Javier Manquillo",
                "Billy Jones",
                "Donald Love",
                "Jack Rodwell",
                "Lee Cattermole",
                "Jan Kirchhoff",
                "Didier Ndong",
                "Sebastian Larsson",
                "Wahbi Khazri",
                "Steven Pienaar",
                "Adnan Januzaj",
                "Lynden Gooch",
                "Fabio Borini",
                "Duncan Watmore",
                "Jermain Defoe",
                "Victor Anichebe"));

        result.put("Middlesbrough", Arrays.asList("Middlesbrough",
                "Víctor Valdes",
                "Dimitrios Konstantopoulos",
                "Tomas Mejias",
                "Bernardo Espinosa",
                "Daniel Ayala",
                "Ben Gibson",
                "Fabio",
                "George Friend",
                "James Husband",
                "Calum Chambers",
                "Antonio Barragán",
                "Emilio Nsue",
                "Julien de Sart",
                "Marten de Roon",
                "Adam Clayton",
                "Adam Forshaw",
                "Grant Leadbitter",
                "Stewart Downing",
                "Carlos de Pena",
                "Gaston Ramirez",
                "Adama Traore",
                "Viktor Fischer",
                "Jordan Rhodes",
                "Alvaro Negredo",
                "Cristhian Stuani",
                "David Nugent"));

        result.put("Tottenham Hotspur", Arrays.asList("Hugo Lloris",
                "Michel Vorm",
                "Pau Lopez",
                "Toby Alderweireld",
                "Jan Vertonghen",
                "Kevin Wimmer",
                "Cameron Carter-Vickers",
                "Danny Rose",
                "Ben Davies",
                "Kyle Walker",
                "Kieran Trippier",
                "Eric Dier",
                "Victor Wanyama",
                "Moussa Sissoko",
                "Dele Alli",
                "Mousa Dembele",
                "Tom Carroll",
                "Harry Winks",
                "Christian Eriksen",
                "Josh Onomah",
                "Georges N'Koudou",
                "Erik Lamela",
                "Heung-Min Son",
                "Harry Kane",
                "Vincent Janssen"));

        result.put("Liverpool", Arrays.asList("Simon Mignolet",
                "Loris Karius",
                "Adam Bogdan",
                "Alexander Manninger",
                "Joel Matip",
                "Dejan Lovren",
                "Mamadou Sakho",
                "Ragnar Klavan",
                "Joe Gomez",
                "Tiago Ilori",
                "Alberto Moreno",
                "Nathaniel Clyne",
                "Connor Randall",
                "Emre Can",
                "Lucas Leiva",
                "Kevin Stewart",
                "Jordan Henderson",
                "James Milner",
                "Marko Grujic",
                "Philippe Coutinho",
                "Georginio Wijnaldum",
                "Adam Lallana",
                "Sadio Mane",
                "Sheyi Ojo",
                "Roberto Firmino",
                "Daniel Sturridge",
                "Danny Ings",
                "Divock Origi"));

        result.put("West Ham United", Arrays.asList("Adrian",
                "Darren Randolph",
                "Raphael Spiegel",
                "Winston Reid",
                "Angelo Ogbonna",
                "Reece Oxford",
                "James Collins",
                "Aaron Cresswell",
                "Arthur Masuaku",
                "Sam Byram",
                "Alvaro Arbeloa",
                "Cheikhou Kouyate",
                "Havard Nordtveit",
                "Pedro Obiang",
                "Mark Noble",
                "Manuel Lanzini",
                "Edimilson Fernandes",
                "Dimitri Payet",
                "Andre Ayew",
                "Sofiane Feghouli",
                "Gokhan Tore",
                "Michail Antonio",
                "Simone Zaza",
                "Diafra Sakho",
                "Andy Carroll",
                "Jonathan Calleri",
                "Ashley Fletcher"));

        result.put("West Bromwich Albion", Arrays.asList("Ben Foster",
                "Boaz Myhill",
                "Jack Rose",
                "Jonny Evans",
                "Jonas Olsson",
                "Gareth McAuley",
                "Brendan Galloway",
                "Craig Dawson",
                "Allan Nyom",
                "Claudio Yacob",
                "James Morrison",
                "Craig Gardner",
                "Darren Fletcher",
                "Chris Brunt",
                "Nacer Chadli",
                "Matt Phillips",
                "Hal Robson-Kanu",
                "James McClean",
                "Callum McManaman",
                "Jonathan Leko",
                "Jose Salomon Rondon",
                "Saido Berahino"));

        result.put("Hull City", Arrays.asList("David Marshall",
                "Allan McGregor",
                "Dusan Kuciak",
                "Eldin Jakupovic",
                "Curtis Davies",
                "Michael Dawson",
                "Harry Maguire",
                "Alex Bruce",
                "Andrew Robertson",
                "Moses Odubajo",
                "Brian Lenihan",
                "Tom Huddlestone",
                "Jake Livermore",
                "Ryan Mason",
                "Markus Henriksen",
                "David Meyler",
                "James Weir",
                "Ahmed Elmohamady",
                "Samuel Clucas",
                "Shaun Maloney",
                "Robert Snodgrass",
                "Abel Hernandez",
                "Dieumerci Mbokani",
                "Will Keane",
                "Adama Diomande",
                "Greg Luer"));

        result.put("Everton", Arrays.asList("Joel Robles",
                "Maarten Stekelenburg",
                "Ramiro Funes Mori",
                "Ashley Williams",
                "Phil Jagielka",
                "Mason Holgate",
                "Matthew Pennington",
                "Leighton Baines",
                "Bryan Oviedo",
                "Seamus Coleman",
                "Tyias Browning",
                "Muhamed Besic",
                "Gareth Barry",
                "James McCarthy",
                "Idrissa Gueye",
                "Tom Cleverley",
                "Darron Gibson",
                "Ross Barkley",
                "Gerard Deulofeu",
                "Aaron Lennon",
                "Yannick Bolasie",
                "Kevin Mirallas",
                "Romelu Lukaku",
                "Oumar Niasse",
                "Enner Valencia",
                "Arouna Kone",
                "Leandro Rodriguez",
                "Conor McAleny"));

        result.put("Bournemouth", Arrays.asList("Artur Boruc",
                "Adam Federici",
                "Ryan Allsop",
                "Steve Cook",
                "Nathan Ake",
                "Marc Wilson",
                "Tyrone Mings",
                "Charlie Daniels",
                "Brad Smith",
                "Simon Francis",
                "Adam Smith",
                "Jack Wilshere",
                "Lewis Cook",
                "Dan Gosling",
                "Andrew Surman",
                "Harry Arter",
                "Emerson Hyndman",
                "Max Gradel",
                "Junior Stanislas",
                "Marc Pugh",
                "Ryan Fraser",
                "Jordon Ibe",
                "Joshua King",
                "Benik Afobe",
                "Callum Wilson",
                "Lys Mousset",
                "Lewis Grabban"));

        result.put("Watford", Arrays.asList("Costel Pantilimon",
                "Giedrius Arlauskis",
                "Heurelho Gomes",
                "Rene Gilmartin",
                "Christian Kabasele",
                "Sebastian Prodl",
                "Craig Cathcart",
                "Miguel Britos",
                "Younes Kaboul",
                "Adrian Mariappa",
                "Jose Holebas",
                "Daryl Janmaat",
                "Brice Dja Djedje",
                "Juan Carlos Paredes",
                "Etienne Capoue",
                "Valon Behrami",
                "Abdoulaye Doucoure",
                "Ben Watson",
                "Adlene Guiedioura",
                "Camilo Zuniga",
                "Roberto Pereyra",
                "Nordin Amrabat",
                "Isaac Success",
                "Odion Ighalo",
                "Troy Deeney",
                "Stefano Okaka",
                "Jerome Sinclair",
                "Mathias Ranegie"));

        result.put("Crystal Palace", Arrays.asList("Steve Mandanda",
                "Wayne Hennessey",
                "Julian Speroni",
                "James Tomkins",
                "Scott Dann",
                "Damien Delaney",
                "Pape Souare",
                "Zeki Fryers",
                "Joel Ward",
                "Martin Kelly",
                "Mathieu Flamini",
                "Yohan Cabaye",
                "James McArthur",
                "Joe Ledley",
                "Jordon Mutch",
                "Bakary Sako",
                "Andros Townsend",
                "Wilfried Zaha",
                "Jason Puncheon",
                "Chung-Yong Lee",
                "Christian Benteke",
                "Loic Remy",
                "Connor Wickham",
                "Fraizer Campbell",
                "Kwesi Appiah"));

        result.put("Swansea City", Arrays.asList("Lukasz Fabianski",
                "Kristoffer Nordfeldt",
                "Mark Birighitti",
                "Gerhard Tremmel",
                "Federico Fernandez",
                "Jordi Amat",
                "Mike van der Hoorn",
                "Alfie Mawson",
                "Neil Taylor",
                "Stephen Kingsley",
                "Kyle Naughton",
                "Angel Rangel",
                "Sung-Yong Ki",
                "Jack Cork",
                "Leroy Fer",
                "Leon Britton",
                "Jay Fulton",
                "Gylfi Sigurdsson",
                "Jefferson Montero",
                "Wayne Routledge",
                "Nathan Dyer",
                "Modou Barrow",
                "Borja Baston",
                "Fernando Llorente"));

        result.put("Stoke City", Arrays.asList("Jack Butland",
                "Jakob Haugaard",
                "Shay Given",
                "Lee Grant",
                "Daniel Bachmann",
                "Ryan Shawcross",
                "Bruno Martins Indi",
                "Marc Muniesa",
                "Geoff Cameron",
                "Dionatan Teixeira",
                "Erik Pieters",
                "Glen Johnson",
                "Phil Bardsley",
                "Giannelli Imbula",
                "Glenn Whelan",
                "Joe Allen",
                "Charlie Adam",
                "Stephen Ireland",
                "Ibrahim Afellay",
                "Ramadan Sobhi",
                "Xherdan Shaqiri",
                "Marko Arnautovic",
                "Jonathan Walters",
                "Bojan Krkic",
                "Wilfried Bony",
                "Mame Diouf",
                "Peter Crouch"));

        return result;
    }

    public Map<String, String> manualSetTeamCity() {
        Map<String, String> result = new HashMap<>();
        result.put("Manchester United", "Manchester");
        result.put("Arsenal", "London");
        result.put("West Bromwich Albion", "West Bromwich");
        result.put("Sunderland", "Sunderland");
        result.put("Liverpool", "Liverpool");
        result.put("West Ham United", "London");
        result.put("Manchester City", "Manchester");
        result.put("Everton", "Liverpool");
        result.put("Middlesbrough", "Middlesbrough");
        result.put("Tottenham Hotspur", "London");
        result.put("Stoke City", "Stoke-on-Trent");
        result.put("Hull City", "Hull");
        result.put("Chelsea", "London");
        result.put("Burnley", "Burnley");
        result.put("Swansea City", "Swansea");
        result.put("Southampton", "Southampton");
        result.put("Crystal Palace", "London");
        result.put("Leicester City", "Leicester");
        result.put("Bournemouth", "Bournemouth");
        result.put("Watford", "Watford");

        return result;
    }
}
